export enum COMPATIBILITY {
  NONE = 'NONE',
  FULL = 'FULL',
  BACKWARD = 'BACKWARD',
  FORWARD = 'FORWARD',
  BACKWARD_TRANSITIVE = 'BACKWARD_TRANSITIVE',
  FORWARD_TRANSITIVE = 'FORWARD_TRANSITIVE',
  FULL_TRANSITIVE = 'FULL_TRANSITIVE',
}

export const DEFAULT_SEPERATOR = '.'

export const DEFAULT_API_CLIENT_ID = 'Confluent_Schema_Registry'
